
# YAML Anchors
x-container-name: &container-name ${CONTAINER_NAME_AUTOHEAL:-autoheal}
x-network-name: &network-name ${CONTAINER_NAME_AUTOHEAL:-autoheal}-internal
x-container-name-proxy: &container-name-proxy ${CONTAINER_NAME_PROXY:-socket-proxy}
x-localtime: &localtime /etc/localtime
x-dockersock: &docker-sock /var/run/docker.sock

x-localtime-bind: &localtimeBindVolume
  type: bind
  source: *localtime
  target: *localtime
  read_only: true

x-label-noautoheal: &label-noautoheal
  autoheal: "false"

x-labels: &fullLabels
  labels:
    <<: *label-noautoheal

x-healthcheck: &healthcheck
  healthcheck:
    test: ["CMD", "/healthcheck.sh"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 5s

x-networks: &networks
  networks:
    - docker-socket-proxy

x-common: &common
    restart: unless-stopped
    <<: [*healthcheck, *networks, *fullLabels]


# Actual Services
services:
  autoheal:
    container_name: *container-name
    image: docker:cli
    <<: *common
    volumes:
      - *localtimeBindVolume
      - type: bind
        source: autoheal.sh
        target: /healthcheck.sh
        read_only: true
    command: sh -c 'echo "Starting ${CONTAINER_NAME_AUTOHEAL}"; sleep infinity'
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
    depends_on:
      - socket-proxy

  socket-proxy:
    container_name: *container-name-proxy
    image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
    <<: *common
    volumes:
      - *localtimeBindVolume
      - type: bind
        source: *docker-sock
        target: *docker-sock
        read_only: false
      - type: bind
        source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg.template
        read_only: true
      - type: bind
        source: server-state
        target: /var/lib/haproxy/server-state
        read_only: true
      - type: bind
        source: healthcheck_proxy.sh
        target: /healthcheck.sh
        read_only: true
    env_file:
      - docker-socket-proxy.env

networks:
  docker-socket-proxy:
    name: *network-name
    driver: bridge
    internal: true